# This file is generated by confctl, changes will be lost
[
  ./org.vpsadminos/int.cache/module.nix
  ./org.vpsadminos/int.images/module.nix
  ./org.vpsadminos/int.iso/module.nix
  ./org.vpsadminos/int.www/module.nix
  ./org.vpsadminos/proxy/module.nix
]
