# This file is generated by confctl, changes will be lost
[
  ./org.vpsadminos/containers/int.bb.master/module.nix
  ./org.vpsadminos/containers/int.bb.nixos01/module.nix
  ./org.vpsadminos/containers/int.bb.nixos02/module.nix
  ./org.vpsadminos/containers/int.cache/module.nix
  ./org.vpsadminos/containers/int.images/module.nix
  ./org.vpsadminos/containers/int.iso/module.nix
  ./org.vpsadminos/containers/int.www/module.nix
  ./org.vpsadminos/containers/proxy/module.nix
]
